# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUsersWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(1636, 600)
        self.label = QtWidgets.QLabel(Widget)
        self.label.setGeometry(QtCore.QRect(360, 10, 461, 20))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_3 = QtWidgets.QLineEdit(Widget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 250, 211, 41))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(Widget)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 70, 171, 41))
        self.lineEdit_4.setStyleSheet("")
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(Widget)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 130, 191, 41))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(Widget)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 190, 191, 41))
        self.lineEdit_6.setText("")
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.pushButton = QtWidgets.QPushButton(Widget)
        self.pushButton.setGeometry(QtCore.QRect(390, 340, 151, 41))
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 47, 255);")
        self.pushButton.setObjectName("pushButton")

        self.pushButton1 = QtWidgets.QPushButton(Widget)
        self.pushButton1.setGeometry(QtCore.QRect(600, 340, 121, 41))
        self.pushButton1.setStyleSheet("color: rgb(255, 255, 255);\n"
                                       "background-color: rgb(0, 65, 255);")

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Окно добавления пользователя"))
        self.label.setText(_translate("Widget", "Панель создания нового пользователя"))
        self.lineEdit_3.setPlaceholderText(_translate("Widget", "Введите должность сотрудника"))
        self.lineEdit_4.setPlaceholderText(_translate("Widget", "Введите  имя сотрудника"))
        self.lineEdit_5.setPlaceholderText(_translate("Widget", "Введите логин сотрудника"))
        self.lineEdit_6.setPlaceholderText(_translate("Widget", "Введите пароль сотрудника"))
        self.pushButton.setText(_translate("Widget", "Добавить сотрудника"))
        self.pushButton1.setText(_translate("Widget", "Выход"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Widget = QtWidgets.QWidget()
    ui = Ui_Widget()
    ui.setupUi(Widget)
    Widget.show()
    sys.exit(app.exec_())
